import { ADMIN_PATH, APP_PATH, AUTH_PATH } from "./path.routes";

export const APP_ROUTES = {
    SIGN_IN: `/${APP_PATH.AUTH}/${AUTH_PATH.SIGN_IN}`,
    DASHBOARD: `/${APP_PATH.ADMIN}/${ADMIN_PATH.DASHBOARD}`,
    PROJECTS: `/${APP_PATH.ADMIN}/${ADMIN_PATH.PROJECTS}`,
    EVENT_LOGS: `/${APP_PATH.ADMIN}/${ADMIN_PATH.EVENT_LOGS}`,
}